# Generated by Django 4.2 on 2024-08-05 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_country', models.CharField(max_length=50)),
                ('artist_biography', models.TextField()),
                ('picture', models.ImageField(upload_to='artist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=4)),
                ('gender', models.CharField(choices=[('Blues', 'Blues'), ('Musica Clasica', 'Musica Clasica'), ('Jzz', 'Jazz'), ('Rap', 'Rap'), ('RGG', 'Reggae'), ('R&B', ' Rhythm and blues'), ('Funk', 'Funk'), ('Rt', 'Reguetón'), ('Soul', 'Soul'), ('Pop', 'Pop'), ('Rock', 'Rock')], max_length=50)),
                ('album_details', models.TextField()),
                ('covers', models.ImageField(upload_to='covers_images')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_manager.artist')),
            ],
        ),
    ]
